// Namespace for EAD xml
var config_eadnamespace = "urn:isbn:1-931666-22-9";

// ContentDM fields. Names must match "field names" in contentdm admin section.
var config_fields = {
	"Title" : undefined,
	"Repository" : undefined,
	"Subarea" : undefined,
	"Collection Number" : undefined,
	"Genre or Form" : undefined,
	"Creator" : undefined,
	"Contributor" : undefined,
	"Date" : undefined,
	"Quantity" : undefined,
	"Language" : undefined,
	"Description" : undefined,
	"Subject" : undefined,
	"Geographical Names" : undefined,
	"Function" : undefined,
	"Occupation" : undefined,
	"Access Restrictions" : undefined,
	"Use Restrictions" : undefined,
	"Alternative Formats Available" : undefined,
	"Related Material" : undefined,
	"Format.xml" : undefined,
};

// XPath queries that map to ContentDM fields
var config_queries = {
	"/ead:ead/ead:archdesc/ead:did/ead:unittitle" : "Title",
	"/ead:ead/ead:archdesc/ead:did/ead:repository/ead:name" : "Repository",
	"/ead:ead/ead:archdesc/ead:did/ead:repository/ead:corpname" : "Repository",
	"/ead:ead/ead:archdesc/ead:did/ead:repository/ead:subarea" : "Subarea",
	"/ead:ead/ead:archdesc/ead:did/ead:unitid" : "Collection Number",
	"/ead:ead/ead:archdesc//ead:controlaccess/ead:genreform" : "Genre or Form",
	"/ead:ead/ead:archdesc/ead:did/ead:origination/ead:corpname" : "Creator",
	"/ead:ead/ead:archdesc/ead:did/ead:origination/ead:famname" : "Creator",
	"/ead:ead/ead:archdesc/ead:did/ead:origination/ead:persname" : "Creator",
	"/ead:ead/ead:archdesc/ead:did/ead:unitdate[@type='inclusive']/@normal" : "Date",
	"/ead:ead/ead:archdesc/ead:did/ead:physdesc/ead:extent" : "Quantity",
	"/ead:ead/ead:archdesc/ead:did/ead:langmaterial/ead:language" : "Language",
	"/ead:ead/ead:archdesc/ead:did/ead:abstract" : "Description",
	"/ead:ead/ead:archdesc/ead:scopecontent/ead:p" : "Description",
	"/ead:ead/ead:archdesc/ead:arrangement/ead:p" : "Description",
	"/ead:ead/ead:archdesc/ead:bioghist/ead:head" : "Description",
	"/ead:ead/ead:archdesc/ead:bioghist/ead:p" : "Description",
	"/ead:ead/ead:archdesc/ead:odd/ead:head|ead:p" : "Description",
	"/ead:ead/ead:archdesc/ead:dsc//ead:did/ead:unittitle" : "Description",
	"/ead:ead/ead:archdesc/ead:dsc//ead:scopecontent/*[not(self::head)]" : "Description",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:geogname" : "Geographical Names",
	"/ead:ead/ead:archdesc//ead:controlaccess/ead:subject[not(@altrender) or @altrender!='nodisplay']" : "Subject",
	"/ead:ead/ead:archdesc//ead:controlaccess/ead:subject[translate(@source, 'UMABROAD', 'umabroad')='umabroad']" : "SubjectBroad",
	"/ead:ead/ead:archdesc//ead:controlaccess/ead:subject[translate(@source, 'UMANARROW', 'umanarrow')='umanarrow']" : "SubjectNarrow",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:persname[@encodinganalog='subject']" : "Subject",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:corpname[@encodinganalog='subject']" : "Subject",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:famname[@encodinganalog='subject']" : "Subject",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:function" : "Subject",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:occupation" : "Subject",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:persname[@encodinganalog='contributor']" : "Contributor",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:corpname[@encodinganalog='contributor']" : "Contributor",
	"/ead:ead/ead:archdesc/ead:controlaccess/ead:famname[@encodinganalog='contributor']" : "Contributor",
	"/ead:ead/ead:archdesc/ead:accessrestrict/ead:p" : "Access Restrictions",
	"/ead:ead/ead:archdesc/ead:userestrict/ead:p" : "Use Restrictions",
	"/ead:ead/ead:archdesc/ead:altformavail/ead:p" : "Alternative Formats Available",
	"/ead:ead/ead:archdesc/ead:relatedmaterial" : "Related Material"
};
